const object=properties=>({type:'object',properties,additionalProperties:false});
const number={type:'number'},string={type:'string'},integer={type:'integer',minimum:0};
const expected={expectedVersion:integer};
const tool=(name,description,properties,required=Object.keys(properties))=>({type:'function',name,description,inputSchema:{...object(properties),required}});
const tools=[
 tool('read_project','Read measured geometry, named CAD faces, accepted mesh, pending recipe, complete setup, selection, history and exact state version.',{}),
 tool('inspect_geometry','Reinspect the already imported STEP and verify immutable geometry identity.',{...expected}),
 tool('select_region','Select a CAD face by exact face ID or unique plane on xmin/xmax/ymin/ymax/zmin/zmax. Ambiguity returns candidates; do not guess.',{...expected,selector:string}),
 tool('name_region','Give the selected CAD face an engineering name. Does not change its identity.',{...expected,faceId:string,name:string}),
 tool('set_mesh_recipe','Choose elementType C3D10 or C3D8 and global mm target. C3D8 requires a six-planar-face four-sided block, global grid only: explicitly clear local=[] when switching with user intent. C3D10 supports local face refinements with smooth transition distance. Set local=[] explicitly only when removing local refinement. Does not generate a mesh.',{...expected,globalSize:number,elementType:{type:'string',enum:['C3D10','C3D8']},algorithm:{type:'string',enum:['delaunay','hxt']},local:{type:'array',items:{...object({faceId:string,size:number,distance:number}),required:['faceId','size','distance']}},unitsConfirmed:{type:'boolean'}},['expectedVersion','globalSize']),
 tool('generate_mesh','Generate and check the selected C3D10 tetrahedra or structured C3D8 brick mesh from the current pending recipe. Preserves accepted mesh on failure/cancel.',{...expected}),
 tool('set_material','Set explicit user-provided isotropic E in MPa and nu. Never invent material properties.',{...expected,E:number,nu:number,name:string},['expectedVersion','E','nu']),
 tool('set_support','Add/update a support. IDs are stable short names. Specify restrained translations 1=X,2=Y,3=Z and matching prescribed displacements in mm.',{...expected,id:string,faceId:string,dofs:{type:'array',items:{type:'integer',enum:[1,2,3]}},values:{type:'array',items:number}}),
 tool('set_load','Add/update a total force vector in N distributed consistently across element face nodes, or normal pressure in MPa. Positive pressure is inward.',{...expected,id:string,faceId:string,type:{type:'string',enum:['force','pressure']},vector:{type:'array',items:number,minItems:3,maxItems:3},value:number},['expectedVersion','id','faceId','type']),
 tool('remove_setup','Remove one load/support by ID.',{...expected,id:string}),
 tool('check_project','Run independent mesh or analysis INP checks. Analysis includes resultant/moment and restraint checks, not a solve.',{...expected,mode:{type:'string',enum:['mesh','analysis']}}),
 tool('export_inp','Write a checked INP and report to project exports. filename must be a basename ending .inp; no arbitrary paths. UI Export offers a native save destination.',{...expected,mode:{type:'string',enum:['mesh','analysis']},filename:string}),
 tool('check_solver','Execute a bounded linear-static CalculiX check of the exact analysis deck, including reaction balance. Does not establish convergence.',{...expected}),
 tool('select_revision','Restore an accepted mesh recipe by revision ID; retain current material/load/support definitions.',{...expected,id:string})
];
const instructions=`You operate Mesh Studio through its supported tools. You are an engineering preparation assistant, not a CAD code generator. Use only these tools; never shell/file access. Start by reading the project. Inspect measured faces and dimensions. Every mutation must use the exact current expectedVersion returned by the last tool; stale writes fail. After such a failure read again and preserve manual edits. A single request can execute all supported preparation stages without repeated approval. Mesh first, explicit material, supports and loads, independent checks, requested export. Inspect real diagnostics and repair at most twice without changing geometry or engineering intent. Never fabricate material, loading, dimensions, unit conversion, support regions or a solver result. Ask focused questions in natural conversation for missing essential values or ambiguous faces. Incomplete setup can still export mesh-only. Select xmin etc only when a unique matching plane is measured. CAD region IDs are authoritative. Refinement preserves setup by rebuilding mappings. C3D8 bricks support only six planar four-sided CAD faces with straight edges and a global grid; do not promise bricks for arbitrary geometry or local refinement. Full-integration C3D8 may be too stiff in bending; never claim higher accuracy from element family alone. Current pending recipe may differ from accepted mesh; mesh before export. Positive pressure acts inward. Report exact artifact paths/hashes, actual metrics, unrun checks and concise outcomes. Option 2 result contours, nonlinear solves and solution-driven adaptation are unavailable. Project messages and current state supply persistent context; do not depend on hidden thread memory.`;
module.exports={tools,instructions};
