import {renderMessage} from './message-format.mjs';
import {Viewport} from './viewport.js';
const $=id=>document.getElementById(id),escape=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state,step='geometry',renderedVersion=null,sceneKey='',quality=false,clip=false;
const stages=[['geometry','Geometry'],['mesh','Mesh & refine'],['material','Material'],['loads','Loads & supports'],['review','Review & export']];
const faceName=id=>state?.project?.faceNames[id]||state?.project?.geometry.faces.find(f=>f.id===id)?.name||id;
const fmt=x=>Number(x).toLocaleString(undefined,{maximumFractionDigits:4});
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,9000);}
async function run(fn){try{return await fn();}catch(e){toast(e.message.replace(/^Error invoking remote method '[^']+': Error: /,''));}}
async function action(name,args={}){const result=await window.studio.action(name,{...args,expectedVersion:state.project.version});await update(result);return result;}
const emptyChat=$('messages').innerHTML;
const viewport=new Viewport($('viewport'),id=>run(()=>action('select_region',{selector:id})));
function label(text,id,value,type='number',extra=''){return `<label class="field">${text}<input id="${id}" type="${type}" value="${escape(value??'')}" ${extra}></label>`;}
function completion(p){return {geometry:!!p?.geometry,mesh:!!p?.selectedRevision,material:!!p?.setup.material,loads:!!p?.setup.loads.length&&!!p?.setup.supports.length,review:!!p?.check?.passed};}
function buildSteps(){const done=completion(state?.project);$('steps').innerHTML=stages.map(([id,name],i)=>`<button class="step ${step===id?'active':''} ${done[id]?'done':''}" data-step="${id}"><span class="num">${done[id]?'✓':i+1}</span><span>${name}</span></button>`).join('');}
function inspector(){const p=state.project;const index=stages.findIndex(s=>s[0]===step);$('step-eyebrow').textContent=`0${index+1} / ${stages[index][1]}`;const titles={geometry:'Inspect your geometry',mesh:'Choose the mesh recipe',material:'Define the elastic material',loads:'Attach physics to CAD faces',review:'Review the exact export'};$('step-title').textContent=titles[step];$('selection-label').textContent=p?.selectedFace?`${faceName(p.selectedFace)} · ${p.selectedFace}`:'No face selected';if(!p){$('inspector-body').innerHTML='<p class="help">Import a STEP or choose a reference part above. The project preserves its source, accepted meshes, setup and conversation.</p>';return;}
 let html='';const r=p.revisions.find(r=>r.id===p.selectedRevision);
 if(step==='geometry'){
  html=`<div class="properties"><div><span>Solid volume</span><strong>${fmt(p.geometry.volume)} mm³</strong></div><div><span>Dimensions</span><strong>${[0,1,2].map(i=>fmt(p.geometry.bounds[i+3]-p.geometry.bounds[i])).join(' × ')} mm</strong></div><div><span>Imported topology</span><strong>${p.geometry.solidCount} solid · ${p.geometry.faces.length} faces</strong></div></div><div class="face-list">${p.geometry.faces.map(f=>`<button data-face="${f.id}" class="${p.selectedFace===f.id?'selected':''}" title="${escape(f.type)} · ${fmt(f.area)} mm²">${escape(faceName(f.id))} <small>${f.id}</small></button>`).join('')}</div><p class="help ${p.geometry.issues.length?'warning':''}">${escape(p.geometry.issues.join(' ')||'Single solid inspected. Pick a face in the model or use the measured face list.')} Source unit: ${escape(p.geometry.sourceUnit)} → mm.</p>`;
  if(p.selectedFace)html+=`<div class="form-row">${label('Selected region name','region-name',faceName(p.selectedFace),'text')}<button data-op="name">Name region</button></div>`;
 }
 if(step==='mesh'){
  const local=p.recipe.local.find(r=>r.faceId===p.selectedFace);
  html=`<div class="form-row">${label('Global target (mm)','global-size',p.recipe.globalSize,'number','min="0.02" step="0.1"')}<label class="field">Algorithm<select id="algorithm"><option value="delaunay" ${p.recipe.algorithm==='delaunay'?'selected':''}>Delaunay</option><option value="hxt" ${p.recipe.algorithm==='hxt'?'selected':''}>HXT</option></select></label><label class="field">Element family<select id="element-type"><option value="C3D10" ${p.recipe.elementType!=='C3D8'?'selected':''}>C3D10 · quadratic tetra</option><option value="C3D8" ${p.recipe.elementType==='C3D8'?'selected':''} ${p.geometry.brickSupported===false||p.geometry.faces.length!==6||p.geometry.faces.some(f=>f.type!=='Plane')?'disabled':''}>C3D8 · linear brick</option></select></label><button data-op="mesh" class="primary">Generate mesh</button></div><div class="form-row">${label('Selected face target (mm)','local-size',local?.size||Math.max(.02,p.recipe.globalSize/2))}${label('Transition distance (mm)','local-distance',local?.distance||p.recipe.globalSize*2)}<button data-op="refine" ${p.selectedFace?'':'disabled'}>Refine selected face</button><button data-op="clear-local">Clear refinements</button></div><div class="item-list">${p.recipe.local.map(x=>`<span class="item">${escape(faceName(x.faceId))}: ${x.size} mm</span>`).join('')}</div><p class="help">${r?`${fmt(r.report.nodeCount)} nodes · ${fmt(r.report.elementCount)} elements · min SICN ${fmt(r.report.minSICN)}. `:''}${r&&JSON.stringify(r.recipe)!==JSON.stringify(p.recipe)?'Settings changed; generate a mesh before export. ':''}C3D8 requires six planar, four-sided faces and straight edges. Clear local refinements before switching; brick size is global. Full-integration bricks may be too stiff in bending. Refinement rebuilds CAD-based load/support sets. Element budget: 150,000; worker timeout: 120 s.</p>`;
  if(p.geometry.sourceUnit==='unrecognized')html+='<label><input id="confirm-units" type="checkbox" '+(p.recipe.unitsConfirmed?'checked':'')+'> I checked the displayed dimensions in millimeters</label>';
 }
 if(step==='material'){const m=p.setup.material;html=`<div class="form-row">${label('Material name','material-name',m?.name||'','text')}${label('Elastic modulus E (MPa)','material-E',m?.E??'','number','placeholder="e.g. 210000"')}${label('Poisson ratio nu','material-nu',m?.nu??'','number','step="0.01" placeholder="e.g. 0.3"')}<button data-op="material" class="primary">Apply material</button></div><p class="help">Explicit homogeneous isotropic linear elasticity. Enter properties for your actual material; Codex will ask when they are missing. No density is needed for the supported static force/pressure cases.</p>`;}
 if(step==='loads'){
  const face=p.selectedFace;html=`<div class="form-row">${label('Item ID','item-id','support','text')}<label class="field">Face<select id="setup-face">${p.geometry.faces.map(f=>`<option value="${f.id}" ${face===f.id?'selected':''}>${escape(faceName(f.id))} (${f.id})</option>`).join('')}</select></label><label class="field">Support directions<select id="support-dofs"><option value="1,2,3">Fixed X, Y, Z</option><option value="1">X only</option><option value="2">Y only</option><option value="3">Z only</option><option value="1,2">X and Y</option><option value="1,3">X and Z</option><option value="2,3">Y and Z</option></select></label>${label('Ux (mm)','support-x',0)}${label('Uy (mm)','support-y',0)}${label('Uz (mm)','support-z',0)}<button data-op="support">Add / update support</button></div><div class="form-row"><label class="field">Load type<select id="load-type"><option value="force">Total force (N)</option><option value="pressure">Pressure (MPa, inward +)</option></select></label>${label('Fx (N)','force-x',0)}${label('Fy (N)','force-y',0)}${label('Fz (N)','force-z',0)}${label('Pressure (MPa)','pressure',0)}<button data-op="load" class="primary">Add / update load</button></div><div class="item-list">${p.setup.supports.map(x=>`<span class="item">⌖ ${escape(x.id)} · ${escape(faceName(x.faceId))} · ${x.dofs.join('/')} <button data-edit="${escape(x.id)}">Edit</button><button data-remove="${escape(x.id)}" aria-label="Remove ${escape(x.id)}">×</button></span>`).join('')}${p.setup.loads.map(x=>`<span class="item">↗ ${escape(x.id)} · ${escape(faceName(x.faceId))} · ${x.type==='force'?x.vector.join(', ')+' N':x.value+' MPa'} <button data-edit="${escape(x.id)}">Edit</button><button data-remove="${escape(x.id)}" aria-label="Remove ${escape(x.id)}">×</button></span>`).join('')}</div><p class="help">Item ID updates an existing definition. Total force uses consistent element face integration. Constraints include every node on the selected face. Review directions and sufficient restraint before analysis export.</p>`;
 }
 if(step==='review'){
  html=`<div class="form-row"><label class="field">Export contents<select id="export-mode"><option value="analysis">Analysis INP</option><option value="mesh">Mesh-only INP</option></select></label><button data-op="check">Check input</button><button data-op="solver">Check with CalculiX</button><button data-op="export" class="primary">Export INP ↗</button></div><div class="checks-list">Mesh: ${r?'checked · min curved Jacobian '+fmt(r.report.minDetJac):'not generated'}<br>Setup: ${p.setup.material&&p.setup.loads.length&&p.setup.supports.length?(p.check?.passed&&p.check.mode==='analysis'?'defined and independently checked':'defined; input checks still required'):'material, load or support missing'}<br>INP: ${p.check?.passed?'independently checked · '+p.check.mode:'not checked for this state'}<br>Solver: ${p.solver?.passed?'executed · reactions balanced':'not run for this state'}<br>Convergence: not established (Option 2)</div><p class="help">${p.exports.length?'Last project export: '+escape(p.exports.at(-1).path):'A mesh-only export is available before analysis setup is complete.'} Export writes a report with the exact mesh revision and SHA-256.</p>`;
 }
 $('inspector-body').innerHTML=html;const family=$('element-type');if(family){const refresh=()=>{$('algorithm').disabled=family.value==='C3D8';for(const op of ['refine'])$('inspector-body').querySelector('[data-op="'+op+'"]').disabled=family.value==='C3D8'||!p.selectedFace;};family.onchange=refresh;refresh();}for(const b of $('inspector-body').querySelectorAll('button'))if(state.busy)b.disabled=true;
}
function chat(){const p=state.project;if(!p?.messages.length&&!state.stream){$('messages').innerHTML=emptyChat;return;}const near=$('messages').scrollHeight-$('messages').scrollTop-$('messages').clientHeight<80;$('messages').innerHTML=(p?.messages||[]).map(m=>`<div class="message ${escape(m.role)}"><span class="who">${m.role==='assistant'?'Codex':m.role==='user'?'You':'Workspace'}</span><div class="message-body">${renderMessage(m.text)}</div></div>`).join('')+(state.stream?`<div class="message streaming"><span class="who">Codex · working</span><div class="message-body">${renderMessage(state.stream)}</div></div>`:'');if(near||state.agentBusy)$('messages').scrollTop=$('messages').scrollHeight;}
function checks(){const p=state.project;if(!p){$('check-tray').innerHTML='';$('check-tray').hidden=true;return;}const r=p.revisions.find(r=>r.id===p.selectedRevision);$('check-tray').innerHTML=`<div class="check-grid"><div>Geometry<strong>${p.geometry.supported?'Single solid':'Inspection only'}</strong></div><div>Mesh<strong>${r?fmt(r.report.elementCount)+' C3D10':'Not generated'}</strong></div><div>Input file<strong>${p.check?.passed?'Checked':'Not checked'}</strong></div><div>Solver<strong>${p.solver?.passed?'Balance passed':'Not run'}</strong></div></div>${r?`<div class="checks-list">minDetJac ${fmt(r.report.minDetJac)} · minSICN ${fmt(r.report.minSICN)} · p05 SICN ${fmt(r.report.p05SICN)} · minSJ ${fmt(r.report.minSJ)}<br>Maximum CAD boundary distance: ${r.report.maxBoundaryDistanceMm.toExponential(2)} mm. ${escape(r.report.warnings.join(' '))}</div>`:''}<div class="history">${p.revisions.map((r,i)=>`<button data-revision="${r.id}">Mesh ${i+1}${r.id===p.selectedRevision?' · selected':''} · ${r.recipe.globalSize} mm</button>`).join('')}<br>${p.history.slice(-8).map(h=>`${escape(h.label)} · v${h.version}`).join(' &nbsp; / &nbsp; ')}</div>`;}
async function update(s){state=s;$('inspector-body').inert=!!s.busy;const p=s.project;if(!p)step='geometry';$('new').disabled=s.busy||s.agentBusy;$('project-title').textContent=p?`${p.title} · state ${p.version} · saved`:'A new analysis starts with geometry';$('status').textContent=s.status;$('connection').textContent=s.connected?(s.agentBusy?'Working':s.plan||'Connected'):'Offline';$('stop').hidden=!(s.busy||s.agentBusy);$('send').disabled=!p||!s.connected||s.agentBusy;$('import').disabled=s.busy||s.agentBusy;$('open').disabled=s.busy||s.agentBusy;$('export').disabled=!p?.selectedRevision||s.busy;$('welcome').hidden=!!p;$('context-token').textContent=p?.selectedFace?`@${faceName(p.selectedFace)} · ${p.selectedFace} · state ${p.version}`:p?`${p.geometry.faces.length} measured CAD faces · state ${p.version}`:'Import geometry to give Codex context';$('scene-label').textContent=p?p.title:'Geometry workspace';const r=p?.revisions.find(r=>r.id===p.selectedRevision);$('scene-detail').textContent=r?`${fmt(r.report.elementCount)} ${r.report.elementType==='C3D8'?'brick elements':'quadratic tetrahedra'} · pick a CAD face`:p?`${p.geometry.solidCount} solid · normalized to millimeters`:'Import a STEP or explore a reference part';const renderKey=p?`${p.folder}|${p.version}|${p.check?.sha256||''}|${p.solver?.deckHash||''}|${p.exports.length}`:'';if(renderKey!==renderedVersion){renderedVersion=renderKey;buildSteps();inspector();checks();}chat();const key=p?`${p.folder}/${p.selectedRevision||'cad'}`:'';if(key!==sceneKey){sceneKey=key;if(p){const data=await window.studio.scene();if(sceneKey===key)viewport.set(data,p.geometry,viewport.geometry?.sourceHash!==p.geometry.sourceHash);if(quality)viewport.quality(true);}else{viewport.reset();quality=false;clip=false;$('clip-control').hidden=true;for(const b of $('display').children)b.classList.toggle('active',b.dataset.mode==='overlay');}}viewport.select(p?.selectedFace);viewport.setup(p);if(s.error&&s.error!==update.lastError){update.lastError=s.error;toast(s.error);}if(!s.error)update.lastError=null;}
$('steps').addEventListener('click',e=>{const b=e.target.closest('[data-step]');if(b){step=b.dataset.step;buildSteps();inspector();}});
$('inspector-body').addEventListener('click',e=>run(async()=>{
 const edit=e.target.closest('[data-edit]');if(edit){const p=state.project;const item=[...p.setup.supports,...p.setup.loads].find(x=>x.id===edit.dataset.edit);$('item-id').value=item.id;$('setup-face').value=item.faceId;if(item.type){$('load-type').value=item.type;if(item.type==='force')item.vector.forEach((v,i)=>$(['force-x','force-y','force-z'][i]).value=v);else $('pressure').value=item.value;}else{$('support-dofs').value=item.dofs.join(',');item.dofs.forEach((d,i)=>$(['support-x','support-y','support-z'][d-1]).value=item.values[i]);}return;}const face=e.target.closest('[data-face]');if(face)return action('select_region',{selector:face.dataset.face});const remove=e.target.closest('[data-remove]');if(remove)return action('remove_setup',{id:remove.dataset.remove});const op=e.target.closest('[data-op]')?.dataset.op;if(!op)return;const p=state.project;const n=id=>{if(!$(id).value.trim())throw Error('Enter '+$(id).closest('label').firstChild.textContent+'.');const x=Number($(id).value);if(!Number.isFinite(x))throw Error('Enter a finite number.');return x;};
 if(op==='name')return action('name_region',{faceId:p.selectedFace,name:$('region-name').value});
 if(op==='mesh'||op==='refine'||op==='clear-local'){
  const args={globalSize:n('global-size'),elementType:$('element-type').value,algorithm:$('algorithm').value,unitsConfirmed:$('confirm-units')?.checked??p.recipe.unitsConfirmed};
  if(op==='refine'){if(args.elementType==='C3D8')throw Error('Bricks use a global structured grid. Choose tetrahedra for local refinement.');args.local=p.recipe.local.filter(x=>x.faceId!==p.selectedFace);args.local.push({faceId:p.selectedFace,size:n('local-size'),distance:n('local-distance')});}
  if(op==='clear-local')args.local=[];await action('set_mesh_recipe',args);if(op!=='clear-local')return action('generate_mesh');return;
 }
 if(op==='material')return action('set_material',{name:$('material-name').value,E:n('material-E'),nu:n('material-nu')});
 if(op==='support'){const dofs=$('support-dofs').value.split(',').map(Number);return action('set_support',{id:$('item-id').value,faceId:$('setup-face').value,dofs,values:dofs.map(d=>n(['support-x','support-y','support-z'][d-1]))});}
 if(op==='load'){const type=$('load-type').value;return action('set_load',{id:$('item-id').value==='support'?'load':$('item-id').value,faceId:$('setup-face').value,type,...(type==='force'?{vector:[n('force-x'),n('force-y'),n('force-z')]}:{value:n('pressure')})});}
 if(op==='check')return action('check_project',{mode:$('export-mode').value});if(op==='solver')return action('check_solver');if(op==='export')return exportINP();
}));
async function exportINP(){const result=await window.studio.exportINP($('export-mode')?.value||'analysis');toast(result.path?'Exported '+result.path:'Saved inside project: '+result.projectPath);await update(await window.studio.state());}
$('new').onclick=()=>run(async()=>{await update(await window.studio.newProject());$('prompt').value='';});
$('import').onclick=$('welcome-import').onclick=()=>run(async()=>update(await window.studio.importSTEP()));$('open').onclick=()=>run(async()=>update(await window.studio.openProject()));$('export').onclick=()=>run(exportINP);$('reveal').onclick=()=>run(()=>window.studio.reveal());
for(const b of document.querySelectorAll('[data-sample]'))b.onclick=()=>run(async()=>update(await window.studio.sample(b.dataset.sample)));
$('display').onclick=e=>{const b=e.target.closest('[data-mode]');if(!b)return;for(const x of $('display').children)x.classList.toggle('active',x===b);viewport.setMode(b.dataset.mode);};$('fit').onclick=()=>viewport.fit();$('quality').onclick=()=>{quality=!quality;viewport.quality(quality);};$('clip').onclick=()=>{clip=!clip;$('clip-control').hidden=!clip;viewport.setClip(clip,Number($('clip-slider').value));};$('clip-slider').oninput=()=>viewport.setClip(clip,Number($('clip-slider').value));
$('checks-toggle').onclick=()=>$('check-tray').hidden=!$('check-tray').hidden;$('check-tray').onclick=e=>{const b=e.target.closest('[data-revision]');if(b)run(()=>action('select_revision',{id:b.dataset.revision}));};$('stop').onclick=()=>run(()=>window.studio.cancel());
async function send(){const text=$('prompt').value.trim();if(!text)return;$('prompt').value='';await update(await window.studio.chat(text));}
$('send').onclick=()=>run(send);$('prompt').onkeydown=e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();run(send);}};
$('messages').addEventListener('click',e=>{if(!e.target.closest('#example'))return;$('prompt').value='Inspect this part. Mesh it at 4 mm, fix the minimum-X plane and apply 1000 N in +X to the maximum-X plane. Use E=210000 MPa and nu=0.3. Check and export a complete CalculiX analysis INP as prepared.inp. Ask if the end faces are ambiguous.';$('prompt').focus();});
function runtime(){const r=state.runtime;$('runtime-list').innerHTML=['python','codex','node','ccx'].map(k=>`<div class="runtime-entry"><span>${k}</span><code>${escape(r[k]||'Not selected')}</code><button data-runtime="${k}">Choose…</button></div>`).join('');}
$('settings').onclick=()=>{runtime();$('runtime-dialog').showModal();};$('close-settings').onclick=()=>$('runtime-dialog').close();$('runtime-list').onclick=e=>{const b=e.target.closest('[data-runtime]');if(b)run(async()=>{await update(await window.studio.runtime(b.dataset.runtime));runtime();});};$('reconnect').onclick=()=>run(async()=>{await update(await window.studio.connect());runtime();});
window.studio.onState(s=>{void update(s).catch(e=>toast(e.message));});window.studio.onCommand(c=>{if(c==='new')$('new').click();if(c==='import')$('import').click();if(c==='open')$('open').click();if(c==='export')$('export').click();});await update(await window.studio.state());
