import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
export class Viewport{
 constructor(container,onSelect){this.container=container;this.onSelect=onSelect;this.mode='overlay';this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#f2f4ed');this.camera=new THREE.PerspectiveCamera(34,1,.01,1e6);this.camera.up.set(0,0,1);this.renderer=new THREE.WebGLRenderer({antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.localClippingEnabled=true;container.prepend(this.renderer.domElement);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.scene.add(new THREE.HemisphereLight(0xffffff,0x6e8065,2.4));const light=new THREE.DirectionalLight(0xffffff,2.2);light.position.set(100,150,200);this.scene.add(light);this.root=new THREE.Group();this.scene.add(this.root);this.symbols=new THREE.Group();this.scene.add(this.symbols);this.raycaster=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.faces=[];
 this.renderer.domElement.addEventListener('pointerdown',e=>{this.down=[e.clientX,e.clientY];});this.renderer.domElement.addEventListener('pointerup',e=>{if(!this.down||Math.hypot(e.clientX-this.down[0],e.clientY-this.down[1])>4)return;const r=this.renderer.domElement.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.raycaster.setFromCamera(this.pointer,this.camera);const hit=this.raycaster.intersectObjects(this.faces)[0];if(hit&&(!this.clipping||hit.point.x<=this.plane.constant))this.onSelect(hit.object.userData.faceId);});
 new ResizeObserver(()=>this.resize()).observe(container);this.resize();this.renderer.setAnimationLoop(()=>{this.controls.update();this.renderer.render(this.scene,this.camera);});
 }
 resize(){const w=this.container.clientWidth,h=this.container.clientHeight;if(!w||!h)return;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h);}
 clear(group){while(group.children.length){const c=group.children[0];c.traverse(o=>{o.geometry?.dispose();if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();}});group.remove(c);}}
 reset(){this.clear(this.root);this.clear(this.symbols);this.faces=[];this.data=null;this.geometry=null;this.bounds=null;this.qualityGroup=null;this.down=null;this.selected=null;this.clipping=false;this.clipPercent=50;this.mode='overlay';}
 set(data,geometry,fit=true){this.clear(this.root);this.faces=[];this.data=data;this.geometry=geometry;if(!data)return;const nodes=new Map(data.nodes.map(n=>[n[0],n.slice(1)]));
 for(const [id,surface] of Object.entries(data.surfaces)){const verts=[];for(const tri of surface.triangles){const subs=tri.length===4?[[0,1,2],[0,2,3]]:tri.length===6?[[0,3,5],[3,1,4],[5,4,2],[3,4,5]]:[[0,1,2]];for(const sub of subs)for(const i of sub)verts.push(...nodes.get(tri[i]));}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));geo.computeVertexNormals();const material=new THREE.MeshStandardMaterial({color:0xd8ded3,roughness:.7,metalness:.08,side:THREE.DoubleSide,polygonOffset:true,polygonOffsetFactor:1});const mesh=new THREE.Mesh(geo,material);mesh.userData.faceId=id;this.faces.push(mesh);this.root.add(mesh);let wireGeometry;if(this.data.elementType==='C3D8'){const edges=[];for(const quad of surface.triangles)for(let i=0;i<4;i++)edges.push(...nodes.get(quad[i]),...nodes.get(quad[(i+1)%4]));wireGeometry=new THREE.BufferGeometry();wireGeometry.setAttribute('position',new THREE.Float32BufferAttribute(edges,3));}else wireGeometry=new THREE.WireframeGeometry(geo);const wire=new THREE.LineSegments(wireGeometry,new THREE.LineBasicMaterial({color:0x678a71,transparent:true,opacity:.35}));wire.userData.wire=true;this.root.add(wire);}
 this.bounds=new THREE.Box3(new THREE.Vector3(...geometry.bounds.slice(0,3)),new THREE.Vector3(...geometry.bounds.slice(3)));this.span=this.bounds.getSize(new THREE.Vector3()).length();this.setMode(this.mode);this.setClip(this.clipping,this.clipPercent??50);if(fit)this.fit();
 }
 fit(){if(!this.bounds)return;const center=this.bounds.getCenter(new THREE.Vector3());this.controls.target.copy(center);const direction=new THREE.Vector3(1.1,-1.35,.9).normalize(),right=new THREE.Vector3().crossVectors(direction,this.camera.up).normalize(),up=new THREE.Vector3().crossVectors(right,direction).normalize();const tan=Math.tan(THREE.MathUtils.degToRad(this.camera.fov/2));let distance=0;for(const x of [this.bounds.min.x,this.bounds.max.x])for(const y of [this.bounds.min.y,this.bounds.max.y])for(const z of [this.bounds.min.z,this.bounds.max.z]){const p=new THREE.Vector3(x,y,z).sub(center);distance=Math.max(distance,p.dot(direction)+Math.max(Math.abs(p.dot(up))/tan,Math.abs(p.dot(right))/(tan*this.camera.aspect)));}this.camera.position.copy(center).add(direction.multiplyScalar(distance*1.15));this.camera.up.set(0,0,1);this.camera.near=Math.max(.001,this.span/10000);this.camera.far=this.span*100;this.camera.updateProjectionMatrix();this.controls.update();}
 setMode(mode){this.mode=mode;for(const c of this.root.children){if(c.userData.wire)c.visible=mode!=='cad';else if(c.material){c.material.transparent=mode==='mesh';c.material.opacity=mode==='mesh'?.2:1;}}}
 select(id){this.selected=id;for(const f of this.faces)f.material.color.set(f.userData.faceId===id?0x69a486:0xd8ded3);}
 setClip(enabled,percent){this.clipping=enabled;this.clipPercent=percent;if(!this.bounds)return;this.plane=new THREE.Plane(new THREE.Vector3(-1,0,0),this.bounds.min.x+(this.bounds.max.x-this.bounds.min.x)*percent/100);this.root.traverse(c=>{if(c.material)c.material.clippingPlanes=enabled?[this.plane]:[];});}
 setup(project){
  this.clear(this.symbols);if(!this.bounds||!project||!this.data)return;const length=this.span*.13,nodes=new Map(this.data.nodes.map(n=>[n[0],new THREE.Vector3(...n.slice(1))])),elements=new Map((this.data.elements||[]).map(e=>[e[0],e.slice(1)]));
  const patchPoint=faceId=>{const tri=this.data.surfaces[faceId]?.triangles[0];if(!tri)return new THREE.Vector3(...project.geometry.faces.find(f=>f.id===faceId).center);return nodes.get(tri[0]).clone().add(nodes.get(tri[1])).add(nodes.get(tri[2])).divideScalar(3);};
  const isBrick=this.data.elementType==='C3D8';const faces=isBrick?[[0,1,2,3],[4,7,6,5],[0,4,5,1],[1,5,6,2],[2,6,7,3],[3,7,4,0]]:[[0,1,2,4,5,6],[0,3,1,7,8,4],[1,3,2,8,9,5],[2,3,0,9,7,6]];
  for(const load of project.setup.loads){const face=project.geometry.faces.find(f=>f.id===load.faceId);if(!face)continue;
   if(load.type==='force'){const direction=new THREE.Vector3(...load.vector);if(direction.length())this.symbols.add(new THREE.ArrowHelper(direction.normalize(),new THREE.Vector3(...face.center),length,0xc4753c,length*.22,length*.1));}
   else{const surface=this.data.surfaces[load.faceId];if(!surface?.elementFaces.length)continue;for(let i=0;i<surface.triangles.length;i+=Math.max(1,Math.floor(surface.triangles.length/5))){const [eid,side]=surface.elementFaces[i],conn=elements.get(eid);const points=faces[side-1].map(j=>nodes.get(conn[j]));const position=new THREE.Vector3(),dr=new THREE.Vector3(),ds=new THREE.Vector3();const N=isBrick?[.25,.25,.25,.25]:[-1/9,-1/9,-1/9,4/9,4/9,4/9],R=isBrick?[-.25,.25,.25,-.25]:[-1/3,1/3,0,0,4/3,-4/3],S=isBrick?[-.25,-.25,.25,.25]:[-1/3,0,1/3,-4/3,4/3,0];for(let j=0;j<N.length;j++){position.addScaledVector(points[j],N[j]);dr.addScaledVector(points[j],R[j]);ds.addScaledVector(points[j],S[j]);}const direction=dr.cross(ds).normalize().multiplyScalar(Math.sign(load.value));if(direction.length())this.symbols.add(new THREE.ArrowHelper(direction,position,length*.7,0xc4753c,length*.15,length*.08));}}
  }
  for(const support of project.setup.supports){const center=patchPoint(support.faceId);for(const d of support.dofs){const direction=new THREE.Vector3();direction.setComponent(d-1,1);this.symbols.add(new THREE.ArrowHelper(direction,center,length*.55,0x5477aa,length*.1,length*.08));}}
 }

 quality(show){if(this.qualityGroup){this.root.remove(this.qualityGroup);this.clear(this.qualityGroup);this.qualityGroup=null;}if(!show||!this.data?.elements)return;this.qualityGroup=new THREE.Group();const nodes=new Map(this.data.nodes.map(n=>[n[0],n.slice(1)]));const worst=new Set(this.data.report.worstElements);const coords=[];for(const e of this.data.elements)if(worst.has(e[0]))for(const [i,j] of (this.data.elementType==='C3D8'?[[1,2],[2,3],[3,4],[4,1],[5,6],[6,7],[7,8],[8,5],[1,5],[2,6],[3,7],[4,8]]:[[1,2],[1,3],[1,4],[2,3],[2,4],[3,4]]))coords.push(...nodes.get(e[i]),...nodes.get(e[j]));const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(coords,3));this.qualityGroup.add(new THREE.LineSegments(geo,new THREE.LineBasicMaterial({color:0xb54d35,depthTest:false})));this.root.add(this.qualityGroup);this.setClip(this.clipping,this.clipPercent??50);}
}
